### ISSUE TITLE
just for help

### ISSUE THREAD

**Issue by Blanceone** [shijungg/tensorflow-cpp-inference#1]
hi shijungg, im looking for source code of libprotobuf.so.14.0.0, but its difficult to find one. i see this in your project. could u share the url with me if u have. thank u very much!

**Comment by shijungg** [comment]
> hi shijungg, im looking for source code of libprotobuf.so.14.0.0, but its difficult to find one. i see this in your project. could u share the url with me if u have. thank u very much!

Sorry, I don't have the source code. But you can refer to https://github.com/protocolbuffers/protobuf/issues/3890, I saw libprotobuf.so.14.0.0 in this issue.

**Comment by Blanceone** [comment]
ok, ill check it. thank u bro!
